#cloud-config
users:
  - name: ubuntu
    shell: /bin/bash
    groups: [sudo]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXh9lICWqv0xmJb6+HDqk8TG/KeAajklBylQK2ftXWY3sjElPBBHONuIxLLc7xlpzXkMl64ebSu/hw698fQtB2z6DNKDRXJo4HyRl00qjtUkmCiajyBDcALlEQv2zxTxlzZJB1ecgton9nacC7Lt3BOCAzegpkv4jnafXfEU4wV/xNyyORYb4LyHjBsro5PtSvuNPJlMR9ROFknl/vo1yEQiNznUMttc2nkXXvS9iVJCm3vWIZr19fhmvfWvoyDIKcku2uegbi8dtKc7+L99kexNGqwhnTMDQqN45Q2jn8msXUPKNUGQvavw6fT5NRmyk5+dNrlKS7hM1FT58GkAa5
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX3LtOduUJMcdvLAXHi1lrkpXp+KyTLk/+WNZSb425e30pfFBNzH3PSOp56U5vKfOHqBaM3rkZEf7Pdcmr9FZRjcDlW3+Rs2uUVhmw/Sov3/CgJ6gbxZfeu4yU6dksrYYh0HtE5aIFI1rPnK7KwDLoTMsOU0cX8rgZGNhj9lzLvNjusH4FRCmZpt2p7vZMVii3rw/NsQ7EGdZAp55Vw9EpaqYbkNL5BkT2KLMdTwPS2d6hL/Uvnr9AL0nQiVjgItO7FvbBkYpfnkDVan2UW7L8hVgUYlfKuQ0JTnuObMQ5JJy6yrQYLO6L1a5Gmab+fXKVYL77EoNOmdrL2rwl2Cj5rNhFJ3eyG6I+fdGzfmJi9429YoT1yEij1JTVe62CX45qWscfAnqk5MOPEtAAoz00HjxSPSUzpXIVA3tqGHIaCcmBacOPvN1JzBMXJMSRLFtS2xBZWYyG5byplRFL1LYDi829+Wxw3ugLTPsYP9LUn10hsFkXvMJr2YyOvZ9ndG8= taher@macbook-pro-von-taher.home

ssh_pwauth: false
disable_root: true

package_update: true
packages:
  - python3
  - python3-venv
  - python3-pip
  - curl
  - unzip

write_files:
  - path: /opt/flaskapp/start.sh
    permissions: '0755'
    content: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd /opt/flaskapp
      if [ ! -d venv ]; then
        echo "[flaskapp] venv not found at /opt/flaskapp/venv. Did you run cloud-init?" >&2
        exit 1
      fi
      source venv/bin/activate
      # Package wird per CD (SSH) in die venv installiert (pip install <wheel>)
      # Entry: python -m app.main  -> erwartet app/main.py mit "app"
      exec python -m app.main

  - path: /etc/systemd/system/flaskapp.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Flask App (my-python-package-2)
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=simple
      User=ubuntu
      Group=ubuntu
      WorkingDirectory=/opt/flaskapp
      ExecStart=/opt/flaskapp/start.sh
      Restart=always
      RestartSec=5
      Environment=PYTHONUNBUFFERED=1
      # Optional robust:
      # UMask=0027
      # LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

runcmd:
  # Basisverzeichnis anlegen & Besitz setzen
  - [ bash, -lc, "mkdir -p /opt/flaskapp && chown -R ubuntu:ubuntu /opt/flaskapp" ]

  # venv als ubuntu anlegen, damit alle Files im Besitz von ubuntu sind
  - [ bash, -lc, "sudo -u ubuntu -H python3 -m venv /opt/flaskapp/venv" ]
  - [ bash, -lc, "sudo -u ubuntu -H /opt/flaskapp/venv/bin/pip install --upgrade pip wheel" ]

  # Service nur registrieren (Start/Enable macht die CD-Pipeline nach dem Deploy)
  - [ bash, -lc, "systemctl daemon-reload" ]

final_message: "Cloud-init complete: base runtime for Flask app prepared (SSH-based CD)."
