#cloud-config

package_update: true
package_upgrade: true
packages:
  - mariadb-server
  - git

runcmd:
  # Bind-Address öffnen
  - sudo sed -i 's/^bind-address\s*=.*$/bind-address = 0.0.0.0/' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo sed -i 's/^bind-address\s*=.*$/bind-address = 0.0.0.0/' /etc/mysql/my.cnf || true
  - sudo systemctl restart mariadb

  # MariaDB absichern
  - sudo mysql -e "DELETE FROM mysql.user WHERE User='';"
  - sudo mysql -e "DROP DATABASE IF EXISTS test;"
  - sudo mysql -e "FLUSH PRIVILEGES;"

  # DB + User anlegen
  - sudo mysql -e "CREATE DATABASE IF NOT EXISTS ecommerce;"
  - sudo mysql -e "CREATE USER IF NOT EXISTS 'shopuser'@'%' IDENTIFIED BY 'password2';"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON ecommerce.* TO 'shopuser'@'%';"
  - sudo mysql -e "FLUSH PRIVILEGES;"

  # Projekt holen
  - mkdir -p /home/ubuntu/ecommerce
  - git clone https://github.com/taher-alsaegh/Flask-Python-E-Commerce-Website.git /home/ubuntu/ecommerce

  # SQL importieren
  - sudo mysql ecommerce < /home/ubuntu/ecommerce/Flask-Python-E-Commerce-Website/ecommerce.sql

